FROM java:8-jdk
MAINTAINER Bernhard Keprt <bernhard.keprt@gmail.com>

RUN apt-get update; apt-get dist-upgrade -y
RUN apt-get install -y 

ENV PATH /usr/bin/java:$PATH
ENV JAVA_HOME /usr/bin/java
